### PR TITLE
Remove obsolete Yarn

### PR DESCRIPTION
**Pull request by jacekk**
Yarn lock file is being 4 month old and NPM lock seems to be the [SSOT](https://en.wikipedia.org/wiki/Single_source_of_truth) when it comes to dependencies. Decided to remove the former one, gitignored, and add a note about that into a relevant doc file. I guess it brings some clarity which package manger should be used.

### CODE REVIEW

**Comment by kirjs** [comment]
Thanks @jacekk, I think this PR makes sense, 

I know there's a bug where for windows users only yarn helped, and npm failed.
I'm going to try reproduce that tomorrow, and see what's the state of things, and if it's safe to drop yarn lock file.

Should be safe to merge after it

**Comment by NothingEverHappens** [comment]
I'm still working on getting a windows laptop, should have it in the next few days :)

**Comment by jacekk** [comment]
@NothingEverHappens @kirjs 
For the last couple days I've been playing with `Win10 (x64) Stable 1809` on a VirtualBox taken from this page: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ . Installing GIT, NodeJS and Yarn went somewhat smooth, but unfortunately, I was not able to install dependencies using NPM. Even running `npm install -ddd --no-bin-links` failed couple times. Usual `npm install` failed as well. Most of those failures were system restart, but some were similar to `npm ERR! { Error: EPERM: operation not permitted`. Most SO advices sounded like **use admin mode** or run `npm cache clean`, but I think those should be unnecessary in normal workflow.

However, `yarn install` went successful in the first try. What is important, `yarn.lock` was not present on the tested branch (the one from this very PR). It is important, because I am aware we loose specific versions of dependencies by removing lockfile for Yarn, but since it was not up to date in coparison to `package-lock.json` versions, I find it even more confusing what I should do right now with this PR.

What's the result of your tests? In case those failed as well, I am totally fine with closing this ticket.

---

P.S.
Installing deps on my linux machine, the `node_modules` directory takes up to **1.5GB** space. Way too much, IMHO.

P.S. 2
I feel really sorry for anyone who is developing bigger nodejs/npm apps on Windows. It's their choice, though :/

**Comment by kirjs** [comment]
Awesome, thanks for the quick merge!

**Comment by kirjs** [comment]
Hey @jacekk, I'm writing a twitter thread about our ivy upgrade, and would like to recognize this PR, as it helped us through the process.
Would it be ok to mention you on twitter, if yes, what's your twitter handle?

**Comment by jacekk** [comment]
@kirjs No Twitter. No Facebook. No LinkedIn. No [you-name-it]. Beside having a GitHub account, I am socially dead ;)

**Pull request merged**
